name: Build Extension ZIP

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Extract version from manifest
        id: get_version
        run: |
          VERSION=$(jq -r .version manifest.json)
          echo "EXT_VERSION=$VERSION" >> $GITHUB_ENV
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: Download-Image-as-PDF-v${{ env.EXT_VERSION }}
          path: |
            .
            ! .git/
            ! .github/
            ! README.md
            ! *.zip